name: Main

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: file-check
        id: get-file
        run: |
          echo "::set-output name=FILES_CHANGED::$(git diff --name-only origin/${{github.base_ref}} origin/${{github.head_ref}} | xargs)"

      - name: echo output
        run: |
          echo "${{ steps.get-file.outputs.FILES_CHANGED }}"

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          echo '${{ steps.file_changes.outputs.files}}'
