name: Main

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: file-check
        id: get-file
        run: |
          DIFF = git diff --name-only origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF}
          echo "::set-output name=FILES_CHANGED::$DIFF"
          echo ${{ steps.get-file.outputs.FILES_CHANGED }}

      - name: echo output
        run: |
          echo "${{ steps.get-file.outputs.FILES_CHANGED }}"

      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          echo '${{ steps.file_changes.outputs.files}}'
