name: Test

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  call-workflow-temp:
    uses: jaycxz/shared-actions/.github/workflows/ci.yaml@master
    with:
      username: "Hello world"
